# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'collageTester' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for collageTester

pod 'BulletinBoard'
pod 'FittedSheets'

  target 'collageTesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'collageTesterUITests' do
    # Pods for testing
  end

end
